{% set name = "http_parser.rb" %}
{% set version = "0.8.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 5a0932f1fa82ce08a8516a2685d5a86031c000560f89946913c555a0697544be

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/ruby_http_parser clean
  skip: {{ win }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r 'http/parser' -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE-MIT
  summary: Ruby bindings to http://github.com/ry/http-parser and http://github.com/a2800276/http-parser.java

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/tmm1/{{ name }}

extra:
  recipe-maintainers:
    - sodre
