travis:
  secure:
    BINSTAR_TOKEN: s1Rcf9qQIMMQZRRd8WUUQgxY2fsKLW9ppC9hI9+R6bzQ4iTD72GI2HJNgee9K5+ABmOsKTAygveBsJFoPfbLjv4HxeboeDONZxIszEPowJLFfVvLM2BkGCJjNaLeP16b6iLHoBUY3AIdwbxf8K3GJsrtlav+8LfP4GpbsMI3X876Gr+P+FmLrV8uZ3Koy1wWr7BKKcX9yUfpYWfRZzr0NVbxueSDFYbwhcficcchKZIzgHO5CC3qIB96nTXSqwBgOHBS2Mg6id0lnipbk/vmrfn7xWIsDrrA+R91gzkJK2Pt+V3uJ4kDtjgwM1h8uqirE9xiZIAhP7yEL2ReVtfCFcyiP1I2mbARfjroZjnnovQG/vbdRn9OaXtKfSnE4RmE6Vv/pspGKbjwcIL67ZENEOodpAsMaAIvtZRyKTxB+bsLmeoQazplVqCP9qFodIiaG6FYElbWzXv5G2hvE+X+tW9dgVPleG9wvQAgQfJZshFa1MH5E4rEdIrNM0OzKUuOWpwNjd50g4IU5eC83dnSV/ogcxujHLt1QA5svn52nkGHQO0piuWPxYXwvMxWCMp2JC+pKg1vSor6ZiDplSSTErBS0uRJbsHBvoWzJEqDfAfg4EWFmudZYu6prbYh4ufRBDT6HEUDWLkUeD+IcqAwlYqdVCsTnNAojB1aupsCr04=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
